### ISSUE TITLE
Lambda API returned error: Invalid Request Content.

### ISSUE THREAD

**Issue by kaihendry** [awsdocs/amazon-aurora-user-guide#8] opened 2019-03-06 03:20 UTC
The stored procedure example on https://github.com/awsdocs/amazon-aurora-user-guide/blob/74b9910506e442963462d371dcb105f492a860fa/doc_source/AuroraMySQL.Integrating.Lambda.md has:
```

   CONCAT('{"email_to" : "', email_to, 
	           '", "email_from" : "', email_from, 
	           '", "email_subject" : "', subject, 
	           '", "email_body" : "', body, '"}')
```

This will fail with a **Invalid Request Content** if there any quotes in body.

Solution I think is to use https://dev.mysql.com/doc/refman/5.7/en/json-creation-functions.html#function_json-quote

Thought I should mention this since we use your example and it is failing from time to time. =)
https://github.com/unee-t/bz-database/issues/118

**Comment by franck-boullier** [comment] 2019-03-06 06:33
Lambda Calls are now using JSON_QUOTE in the DEV/Staging and in the DEMO envo.
We need to check if this fix works as intended.

**Comment by franck-boullier** [comment] 2019-03-06 08:52
> Lambda Calls are now using JSON_QUOTE in the DEV/Staging and in the DEMO envo.

We had to revert back that change as this created invalid JSON.
@kaihendry do I still need to explore ways to use JSON_QUOTE or comparable methods or are we looking for another culprit/solution for this issue?

**Comment by joshbean** [comment] 2023-06-15 23:20
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).

**Closed as completed by joshbean** 2023-06-15 23:20 UTC
Labels: archived
